# Generated by Django 3.2.4 on 2022-02-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
